@startuml
sprite $smile [16x16/16] {
FFFFFFFFFFFFFFFF
FFFFFF0000FFFFFF
FFFFF0FFFF0FFFFF
FFFF0FFFFFF0FFFF
FFF0FFFFFFFF0FFF
FF0F000FF000F0FF
F0F0FFF00FFF0F0F
F0FFFFFFFFFFFF0F
F0FFFFFFFFFFFF0F
F0FFF0FFFF0FFF0F
FF0FFF0FF0FFF0FF
FFF0FFF00FFF0FFF
FFFF0FFFFFF0FFFF
FFFFF0FFFF0FFFFF
FFFFFF0000FFFFFF
FFFFFFFFFFFFFFFF
}


rectangle "Shopping System\n(pricing)" <<$smile>> {
 rectangle "pricing service" <<$smile>> as src
 rectangle "pricing engine" <<$smile>> as tgt
 src -> tgt
}
@enduml